# Loads a dataset pre-generated by data/generate.py (scripts/make_dataset.py)
# from its HDF5 file. This is the ONLY data path a run uses -- no run ever
# regenerates trajectories on the fly (see project README). Ported from
# Tests/Model_in_tests/full_rollout_training_conv1d/training/code/dataset.py's
# load_hdf5_dataset/compute_norm_stats.
from __future__ import annotations

import numpy as np
import pandas as pd

from .windows import build_window, make_feature_columns, make_output_columns
from ..physics.waves import apply_boundary

# The 6 driving families data/generate.py's "complex" profile draws from --
# used to pick one held-out showcase trajectory per family (analysis/plots).
SHOWCASE_FAMILIES = ["fourier", "sinusoid", "chirp", "gaussian", "shock", "filtered_random"]

# data/generate.py's 3 boundary "type" labels -> this project's
# dirichlet/neumann vocabulary. "Displacement" and "Velocity (integrated)"
# are both prescribed-value (dirichlet) ends -- they only differ in how the
# driving family's raw output was turned into a value before being stored,
# already baked into left_bc_value/right_bc_value by the time this is read.
BC_LABEL_TO_TYPE = {
    "Displacement": "dirichlet",
    "Force (du/dx)": "neumann",
    "Velocity (integrated)": "dirichlet",
}


def _decode_str_array(arr) -> list[str]:
    return [v.decode() if isinstance(v, bytes) else v for v in arr]


def _reconstruct_full_state(u_nx: np.ndarray, left_values: np.ndarray, right_values: np.ndarray,
                             left_type: str, right_type: str, cfg) -> np.ndarray:
    # u_nx: (Nt+1, Nx), the physical-node-only trajectory data/generate.py
    # stores (no ghost band). Rebuilds the full (Nt+1, Ntot) array this
    # project's physics/rollout code expects by re-filling the ghost band at
    # every step from the already-computed boundary values.
    #
    # Known approximation at index i_right for a Neumann RIGHT boundary:
    # waves.apply_boundary deliberately leaves a Neumann boundary's own node
    # untouched, and i_right is one past the last stored column (u_nx[:,-1]
    # maps to i_right-1) -- so its true value was never saved and is
    # approximated here as a copy of its nearest physical neighbor. Exact for
    # Dirichlet; affects only the stencil features within SS of the right
    # edge, only for Neumann-right trajectories.
    n_steps = u_nx.shape[0]
    u_full = np.zeros((n_steps, cfg.Ntot), dtype=np.float32)
    u_full[:, cfg.i_left:cfg.i_right] = u_nx
    if right_type != "dirichlet":
        u_full[:, cfg.i_right] = u_nx[:, -1]
    for n in range(n_steps):
        apply_boundary(u_full[n], "left", left_type, float(left_values[n]), cfg)
        apply_boundary(u_full[n], "right", right_type, float(right_values[n]), cfg)
    return u_full


def _window_trajectory(idx, u_storage, input_fields, cfg, INPUTS, OUTPUTS) -> pd.DataFrame:
    nodes = cfg.nodes
    n_list = list(range(cfg.M_BACK * cfg.ndt, cfg.Nt - cfg.N_FWD * cfg.ndt + 1))

    X = np.zeros((len(n_list), len(nodes), len(INPUTS)), dtype=np.float32)
    Y = np.zeros((len(n_list), len(nodes), len(OUTPUTS)), dtype=np.float32)
    for i, n in enumerate(n_list):
        m_list = [n - lag * cfg.ndt for lag in range(cfg.M_BACK)]
        X[i] = build_window(m_list, lambda m: u_storage[m], input_fields, cfg)
        for h in range(1, cfg.N_FWD + 1):
            Y[i, :, h - 1] = u_storage[n + h * cfg.ndt, nodes] - u_storage[n, nodes]

    meta = pd.DataFrame({"sim_idx": idx, "n_step": np.repeat(n_list, len(nodes))})
    return pd.concat([
        meta.reset_index(drop=True),
        pd.DataFrame(X.reshape(-1, len(INPUTS)), columns=INPUTS),
        pd.DataFrame(Y.reshape(-1, len(OUTPUTS)), columns=OUTPUTS),
    ], axis=1)


def _pick_family_showcase(left_family, right_family, left_driven, right_driven, split_label, n_total) -> dict:
    showcase = {}
    for allowed_splits in (("val", "test"), ("train", "val", "test")):
        for idx in range(n_total):
            if split_label[idx] not in allowed_splits:
                continue
            if left_driven[idx] and left_family[idx] in SHOWCASE_FAMILIES and left_family[idx] not in showcase:
                showcase[left_family[idx]] = idx
            if right_driven[idx] and right_family[idx] in SHOWCASE_FAMILIES and right_family[idx] not in showcase:
                showcase[right_family[idx]] = idx
        if len(showcase) == len(SHOWCASE_FAMILIES):
            break
    return showcase


def load_hdf5_dataset(input_fields, cfg, h5_path, max_trajectories=None):
    # Returns (df, FIELDS, INPUTS, OUTPUTS, bc_pairs, idx_train, idx_val,
    # idx_test, rollout_idx, family_showcase_idx). Each boundary end's
    # per-step value series is wrapped as a "table" BC_WAVEFORMS entry (see
    # physics/waves.py) so bc_value(bc, t)/apply_boundary_conditions keep
    # working unmodified during rollout/training.
    import h5py  # deferred: only needed by this function

    with h5py.File(h5_path, "r") as f:
        n_total = f["u"].shape[0] if max_trajectories is None else min(max_trajectories, f["u"].shape[0])
        u = f["u"][:n_total]
        left_bc_value = f["left_bc_value"][:n_total]
        right_bc_value = f["right_bc_value"][:n_total]
        left_label = _decode_str_array(f["left_label"][:n_total])
        right_label = _decode_str_array(f["right_label"][:n_total])
        left_family = _decode_str_array(f["left_family"][:n_total])
        right_family = _decode_str_array(f["right_family"][:n_total])
        left_driven = f["left_driven"][:n_total]
        right_driven = f["right_driven"][:n_total]
        split_label = _decode_str_array(f["split"][:n_total])

    INPUTS = make_feature_columns(input_fields, cfg)
    OUTPUTS = make_output_columns(cfg)
    t_ctrl = (np.arange(cfg.Nt + 1) * cfg.dt).tolist()

    FIELDS, bc_pairs, dfs = {}, [], []
    idx_by_split = {"train": [], "val": [], "test": []}
    for idx in range(n_total):
        left_type = BC_LABEL_TO_TYPE[left_label[idx]]
        right_type = BC_LABEL_TO_TYPE[right_label[idx]]
        u_full = _reconstruct_full_state(u[idx], left_bc_value[idx], right_bc_value[idx],
                                          left_type, right_type, cfg)
        FIELDS[idx] = u_full

        bc_pairs.append((
            (left_type, "table", {"t_ctrl": t_ctrl, "values": left_bc_value[idx].tolist(),
                                   "source_label": left_label[idx]}),
            (right_type, "table", {"t_ctrl": t_ctrl, "values": right_bc_value[idx].tolist(),
                                    "source_label": right_label[idx]}),
        ))

        dfs.append(_window_trajectory(idx, u_full, input_fields, cfg, INPUTS, OUTPUTS))
        idx_by_split[split_label[idx]].append(idx)

    df = pd.concat(dfs, ignore_index=True)
    split_df = pd.DataFrame(
        [(i, s) for s, idxs in idx_by_split.items() for i in idxs],
        columns=["sim_idx", "split"],
    )
    df = df.merge(split_df, on="sim_idx", how="left")

    idx_train, idx_val, idx_test = idx_by_split["train"], idx_by_split["val"], idx_by_split["test"]
    rollout_idx = idx_test[0]
    family_showcase_idx = _pick_family_showcase(left_family, right_family, left_driven, right_driven,
                                                 split_label, n_total)

    print(f"Loaded {n_total} trajectories from {h5_path}")
    print("Split distribution (from dataset):")
    for s, idxs in idx_by_split.items():
        print(f"  {s:5s} : {len(idxs):>4d} simulations ({100*len(idxs)/n_total:.1f} %)")

    return df, FIELDS, INPUTS, OUTPUTS, bc_pairs, idx_train, idx_val, idx_test, rollout_idx, family_showcase_idx


def compute_norm_stats(df: pd.DataFrame, INPUTS, OUTPUTS, cfg) -> pd.DataFrame:
    train_mask = df["split"] == "train"
    cols = INPUTS + OUTPUTS
    norm_stats = pd.DataFrame({
        "mean": df.loc[train_mask, cols].mean(),
        "std": df.loc[train_mask, cols].std(),
    })
    norm_stats["std"] = norm_stats["std"].replace(0, 1)
    return norm_stats
