# Loads a dataset pre-generated by data/generate.py (dataset/make_dataset.py)
# from its HDF5 file. This is the ONLY data path a run uses -- no run ever
# regenerates trajectories on the fly (see project README). Ported from
# Tests/Model_in_tests/full_rollout_training_conv1d/training/code/dataset.py's
# load_hdf5_dataset/compute_norm_stats.
from __future__ import annotations

import numpy as np
import pandas as pd

from .windows import build_window, make_feature_columns, make_output_columns
from ..physics.waves import apply_boundary

# The 6 driving families data/generate.py's "complex" profile draws from --
# used to pick one held-out showcase trajectory per family (analysis/plots).
SHOWCASE_FAMILIES = ["fourier", "sinusoid", "chirp", "gaussian", "shock", "filtered_random",
                      "sine_pulse", "triangular", "sawtooth", "square"]

# data/generate.py's 3 boundary "type" labels -> this project's
# dirichlet/neumann vocabulary. "Displacement" and "Velocity (integrated)"
# are both prescribed-value (dirichlet) ends -- they only differ in how the
# driving family's raw output was turned into a value before being stored,
# already baked into left_bc_value/right_bc_value by the time this is read.
BC_LABEL_TO_TYPE = {
    "Displacement": "dirichlet",
    "Force (du/dx)": "neumann",
    "Velocity (integrated)": "dirichlet",
}


def _decode_str_array(arr) -> list[str]:
    return [v.decode() if isinstance(v, bytes) else v for v in arr]


def _reconstruct_full_state(u_nx: np.ndarray, left_values: np.ndarray, right_values: np.ndarray,
                             left_type: str, right_type: str, cfg) -> np.ndarray:
    # u_nx: (Nt+1, Nx), the physical-node-only trajectory data/generate.py
    # stores (no ghost band). Rebuilds the full (Nt+1, Ntot) array this
    # project's physics/rollout code expects by re-filling the ghost band at
    # every step from the already-computed boundary values.
    #
    # Known approximation at index i_right for a Neumann RIGHT boundary:
    # waves.apply_boundary deliberately leaves a Neumann boundary's own node
    # untouched, and i_right is one past the last stored column (u_nx[:,-1]
    # maps to i_right-1) -- so its true value was never saved and is
    # approximated here as a copy of its nearest physical neighbor. Exact for
    # Dirichlet; affects only the stencil features within SS of the right
    # edge, only for Neumann-right trajectories.
    n_steps = u_nx.shape[0]
    u_full = np.zeros((n_steps, cfg.Ntot), dtype=np.float32)
    u_full[:, cfg.i_left:cfg.i_right] = u_nx
    if right_type != "dirichlet":
        u_full[:, cfg.i_right] = u_nx[:, -1]
    for n in range(n_steps):
        apply_boundary(u_full[n], "left", left_type, float(left_values[n]), cfg)
        apply_boundary(u_full[n], "right", right_type, float(right_values[n]), cfg)
    return u_full


def _window_trajectory_into(u_storage, input_fields, cfg, n_list, X_out: np.ndarray, Y_out: np.ndarray) -> None:
    # Fills X_out (rows_per_traj, len(INPUTS)) and Y_out (rows_per_traj,
    # len(OUTPUTS)) in place -- these are views into one big pre-allocated
    # array covering every trajectory (see load_hdf5_dataset), not a
    # standalone array. Row order is (n_step, node), must match
    # n_step_all's np.repeat(n_list, n_nodes) below. Filling in place instead
    # of returning a fresh per-trajectory DataFrame avoids ever holding both
    # the per-trajectory tables AND their pd.concat'd combination in memory
    # at once.
    nodes = cfg.nodes
    n_nodes = len(nodes)
    for i, n in enumerate(n_list):
        m_list = [n - lag * cfg.ndt for lag in range(cfg.M_BACK)]
        row0 = i * n_nodes
        X_out[row0:row0 + n_nodes] = build_window(m_list, lambda m: u_storage[m], input_fields, cfg)
        for h in range(1, cfg.N_FWD + 1):
            Y_out[row0:row0 + n_nodes, h - 1] = u_storage[n + h * cfg.ndt, nodes] - u_storage[n, nodes]


def _pick_family_showcase(left_family, right_family, left_driven, right_driven, split_label, n_total) -> dict:
    showcase = {}
    for allowed_splits in (("val", "test"), ("train", "val", "test")):
        for idx in range(n_total):
            if split_label[idx] not in allowed_splits:
                continue
            if left_driven[idx] and left_family[idx] in SHOWCASE_FAMILIES and left_family[idx] not in showcase:
                showcase[left_family[idx]] = idx
            if right_driven[idx] and right_family[idx] in SHOWCASE_FAMILIES and right_family[idx] not in showcase:
                showcase[right_family[idx]] = idx
        if len(showcase) == len(SHOWCASE_FAMILIES):
            break
    return showcase


def load_hdf5_dataset(input_fields, cfg, h5_path, max_trajectories=None):
    # Returns (df, FIELDS, INPUTS, OUTPUTS, bc_pairs, idx_train, idx_val,
    # idx_test, rollout_idx, family_showcase_idx). Each boundary end's
    # per-step value series is wrapped as a "table" BC_WAVEFORMS entry (see
    # physics/waves.py) so bc_value(bc, t)/apply_boundary_conditions keep
    # working unmodified during rollout/training.
    import h5py  # deferred: only needed by this function

    with h5py.File(h5_path, "r") as f:
        n_total = f["u"].shape[0] if max_trajectories is None else min(max_trajectories, f["u"].shape[0])
        u = f["u"][:n_total]
        left_bc_value = f["left_bc_value"][:n_total]
        right_bc_value = f["right_bc_value"][:n_total]
        left_label = _decode_str_array(f["left_label"][:n_total])
        right_label = _decode_str_array(f["right_label"][:n_total])
        left_family = _decode_str_array(f["left_family"][:n_total])
        right_family = _decode_str_array(f["right_family"][:n_total])
        left_driven = f["left_driven"][:n_total]
        right_driven = f["right_driven"][:n_total]
        split_label = _decode_str_array(f["split"][:n_total])

    INPUTS = make_feature_columns(input_fields, cfg)
    OUTPUTS = make_output_columns(cfg)
    t_ctrl = (np.arange(cfg.Nt + 1) * cfg.dt).tolist()

    # Every trajectory windows to the same row count (n_list/nodes only
    # depend on cfg, not on the trajectory), so the full table's size is
    # known up front -- one allocation, filled trajectory by trajectory,
    # rather than 3000 small tables later pd.concat'd together (see
    # _window_trajectory_into's docstring for why that mattered).
    n_list = list(range(cfg.M_BACK * cfg.ndt, cfg.Nt - cfg.N_FWD * cfg.ndt + 1))
    n_nodes = len(cfg.nodes)
    rows_per_traj = len(n_list) * n_nodes
    total_rows = n_total * rows_per_traj
    n_in, n_out = len(INPUTS), len(OUTPUTS)

    data_all = np.empty((total_rows, n_in + n_out), dtype=np.float32)
    sim_idx_all = np.empty(total_rows, dtype=np.int32)
    n_step_all = np.empty(total_rows, dtype=np.int32)
    split_code_all = np.empty(total_rows, dtype=np.int8)
    split_categories = ["train", "val", "test"]
    split_code_of = {s: i for i, s in enumerate(split_categories)}

    FIELDS, bc_pairs = {}, []
    idx_by_split = {"train": [], "val": [], "test": []}
    for idx in range(n_total):
        left_type = BC_LABEL_TO_TYPE[left_label[idx]]
        right_type = BC_LABEL_TO_TYPE[right_label[idx]]
        u_full = _reconstruct_full_state(u[idx], left_bc_value[idx], right_bc_value[idx],
                                          left_type, right_type, cfg)
        FIELDS[idx] = u_full

        bc_pairs.append((
            (left_type, "table", {"t_ctrl": t_ctrl, "values": left_bc_value[idx].tolist(),
                                   "source_label": left_label[idx]}),
            (right_type, "table", {"t_ctrl": t_ctrl, "values": right_bc_value[idx].tolist(),
                                    "source_label": right_label[idx]}),
        ))

        start = idx * rows_per_traj
        end = start + rows_per_traj
        _window_trajectory_into(u_full, input_fields, cfg, n_list,
                                 data_all[start:end, :n_in], data_all[start:end, n_in:])
        sim_idx_all[start:end] = idx
        n_step_all[start:end] = np.repeat(n_list, n_nodes)
        split_code_all[start:end] = split_code_of[split_label[idx]]
        idx_by_split[split_label[idx]].append(idx)

    # copy=False: data_all becomes df's single backing block instead of
    # being duplicated into one -- the sim_idx/n_step/split columns added
    # after are comparatively tiny (int32/int8, not float32 x 49 columns).
    df = pd.DataFrame(data_all, columns=INPUTS + OUTPUTS, copy=False)
    df["sim_idx"] = sim_idx_all
    df["n_step"] = n_step_all
    df["split"] = pd.Categorical.from_codes(split_code_all, categories=split_categories)

    idx_train, idx_val, idx_test = idx_by_split["train"], idx_by_split["val"], idx_by_split["test"]
    rollout_idx = idx_test[0]
    family_showcase_idx = _pick_family_showcase(left_family, right_family, left_driven, right_driven,
                                                 split_label, n_total)

    print(f"Loaded {n_total} trajectories from {h5_path}")
    print("Split distribution (from dataset):")
    for s, idxs in idx_by_split.items():
        print(f"  {s:5s} : {len(idxs):>4d} simulations ({100*len(idxs)/n_total:.1f} %)")

    return df, FIELDS, INPUTS, OUTPUTS, bc_pairs, idx_train, idx_val, idx_test, rollout_idx, family_showcase_idx


def compute_norm_stats(df: pd.DataFrame, INPUTS, OUTPUTS, cfg, chunk_rows: int = 2_000_000) -> pd.DataFrame:
    # Filters the train split ONCE (not once per statistic) into a plain
    # numpy array, then reduces it chunk by chunk with float64 accumulators
    # -- NOT via train_block.std(dtype=np.float64), whose internal
    # `array - mean` step would materialize a full copy of train_block AT
    # FLOAT64 WIDTH (2x its float32 size) just to compute deviations. At the
    # full dataset's scale (~28G float32) that's an extra ~56G, which is
    # what pushed a real run past a 96G Slurm --mem limit. Chunking keeps
    # memory bounded by chunk_rows regardless of dataset size, while still
    # accumulating in float64 (a naive float32 sum over millions of rows
    # loses meaningful precision) -- ddof=1 matches pandas' own .std() default.
    cols = INPUTS + OUTPUTS
    train_mask = (df["split"] == "train").to_numpy()
    train_block = df[cols].to_numpy(copy=False)[train_mask]
    n_rows, n_cols = train_block.shape

    sum_ = np.zeros(n_cols, dtype=np.float64)
    for start in range(0, n_rows, chunk_rows):
        sum_ += train_block[start:start + chunk_rows].sum(axis=0, dtype=np.float64)
    mean = sum_ / n_rows

    sq_dev_sum = np.zeros(n_cols, dtype=np.float64)
    for start in range(0, n_rows, chunk_rows):
        dev = train_block[start:start + chunk_rows].astype(np.float64) - mean
        sq_dev_sum += (dev * dev).sum(axis=0)
    std = np.sqrt(sq_dev_sum / (n_rows - 1))

    norm_stats = pd.DataFrame({"mean": mean, "std": std}, index=cols)
    norm_stats["std"] = norm_stats["std"].replace(0, 1)
    return norm_stats
