# Single source of truth for every run parameter of this project. Defaults
# below are the values THIS project actually trains with: a composite loss
# made of three terms computed together in the same optimizer step --
# rollout (TBPTT autoregressive prediction error), physics (wave-equation
# residual, u_tt - (E/rho)*u_xx), and data (plain one-step teacher-forcing
# error on an independent batch) -- not a generic 4-project default silently
# overridden elsewhere (main.py used to carry a separate CONFIG_OVERRIDES
# dict on top of a shared commun.Config() with different defaults; that
# indirection is gone, this is the only Config now). N_EPOCHS/BATCH_SIZE/
# GROUP_SIZE/TBPTT_HOPS/LAMBDA_* still vary at the call site (main.py's CLI
# flags) -- that's a real per-run knob, not leftover cross-project
# indirection.
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import torch


@dataclass
class Config:
    E: float = 1
    rho: float = 2
    L: float = 1

    Nt: int = 500
    Nx: int = 100
    SS: int = 10
    t_end: float = 5

    # M_BACK past levels -> N_FWD future horizons, spaced by ndt steps.
    ndt: int = 2
    M_BACK: int = 2
    N_FWD: int = 2

    # Sampling ranges for waves.py's families -- only used by the on-the-fly
    # generation path (scenarios.py + dataset.generate_dataset_multisignal),
    # which main.py's own training path no longer calls (it loads a dataset
    # pre-generated by Dataset/Creation_dataset.py instead, whose OWN
    # amplitude/frequency ranges are already baked into that file and can
    # differ from these). Still real for check_equivalence.py's
    # scenarios.sample_random_ic call and any other standalone use of the
    # on-the-fly path.
    AMP_MIN: float = 0.01
    AMP_MAX: float = 0.20
    OMEGA_MIN: float = 0.05
    OMEGA_MAX: float = 0.5

    LEARNING_RATE: float = 1e-3
    N_EPOCHS: int = 50
    BATCH_SIZE: int = 32

    # TBPTT rollout: GROUP_SIZE simulations advanced together, corrected
    # (backward+step) every TBPTT_HOPS hops.
    GROUP_SIZE: int = 8
    TBPTT_HOPS: int = 10

    # Composite loss weights: total = LAMBDA_ROLLOUT*rollout_loss +
    # LAMBDA_PHYSICS*physics_loss + LAMBDA_DATA*data_loss, all three summed
    # into one scalar before a single backward()+step() -- see train.py.
    # LAMBDA_PHYSICS can't be derived analytically (the residual is a raw
    # physical quantity, not z-scored like the data/rollout MSE terms) --
    # 0.01 is a starting point to tune empirically against the logged,
    # unweighted per-term losses.
    LAMBDA_DATA: float = 1.0
    LAMBDA_PHYSICS: float = 0.01
    LAMBDA_ROLLOUT: float = 1.0

    NOISE_STD: float = 0.1
    SMOOTH_ALPHA: float = 0.20   # must stay < 0.25 (smoothing stability)

    SEED: int = 0
    # Only used by the on-the-fly path's dataset.split_by_simulation --
    # dataset.load_hdf5_dataset (main.py's actual path) reuses the
    # train/val/test split already baked into the HDF5 file instead.
    SPLIT_SEED: int = 42

    # 0 disables early stopping (always run the full N_EPOCHS). Consecutive
    # epochs allowed without a new best val loss before training stops.
    EARLY_STOP_PATIENCE: int = 15

    def __post_init__(self):
        self.Ntot = self.Nx + 2 * self.SS
        self.i_left = self.SS
        self.i_right = self.Ntot - self.SS
        self.nodes = np.arange(self.i_left, self.i_right)
        self.dt = self.t_end / self.Nt
        self.dx = self.L / (self.Nx - 1)
        self.CFL = self.dt / self.dx * np.sqrt(self.E / self.rho)
        if self.CFL > 1:
            print(f"WARNING: CFL={self.CFL:.3f} > 1 -- the explicit scheme is numerically "
                  f"unstable with these Nt/Nx/t_end/L (the simulation will diverge). Increase Nt "
                  f"and/or reduce Nx to bring CFL back to <= 1.")


def set_seeds(cfg: Config) -> None:
    torch.manual_seed(cfg.SEED)
    np.random.seed(cfg.SEED)
