# Entry point: composite-loss training of the Conv1d model (model.py) --
# every weight update combines THREE terms in one backward()+step():
#   - rollout: autoregressive TBPTT prediction error, chained hop by hop
#     over whole simulations, never reset to ground truth (train.py).
#   - physics: wave-equation residual (u_tt - (E/rho)*u_xx), computed for
#     free from the same tensors the rollout term already produces.
#   - data: plain one-step MSE on an independent batch drawn straight from
#     the flattened dataset (df/INPUTS/OUTPUTS), same mechanism this
#     project's dataloaders (training.make_dataloaders) always used.
# total = LAMBDA_ROLLOUT*rollout + LAMBDA_PHYSICS*physics + LAMBDA_DATA*data
# -- see config.py for the weights and train.train_full_rollout for the loop.
#
# Trains on trajectories pre-generated by Dataset/Creation_dataset.py and
# saved to one HDF5 file (dataset.load_hdf5_dataset), not on scenarios
# simulated on the fly -- that on-the-fly path (scenarios.py +
# dataset.generate_dataset_multisignal/split_by_simulation) still exists for
# standalone use (check_equivalence.py's free-evolution case still needs
# scenarios.sample_random_ic) but main.py itself no longer calls it.
import argparse
import resource
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from config import Config, set_seeds
from waves import bc_describe
from model import ConvNet
import dataset
import training
import train
import evaluation

# U only: the network only ever sees past displacement at each node, no
# velocity (Ut) or curvature (Uxx) features -- same convention as
# full_rollout_training_multisignal.
INPUT_FIELDS = ["U"]
METHOD_NAME = "conv1d_U_multisignal_composite_rollout_physics_data"

# code/ is a subfolder of full_rollout_training_conv1d/training/ -- plots/
# and logs/ are its sibling folders; model.pth/norm_stats.csv stay at the
# full_rollout_training_conv1d/ level.
TRAINING_DIR = SCRIPT_DIR.parent
PROJECT_DIR = TRAINING_DIR.parent
PLOTS_DIR = TRAINING_DIR / "plots"

# Code_GH/Dataset/beam_dataset.h5 -- computed relative to this file (not a
# hardcoded absolute path) so it still resolves on any machine/checkout.
# code -> training -> full_rollout_training_conv1d -> Model_in_tests -> Tests -> Code_GH.
REPO_ROOT = PROJECT_DIR.parent.parent.parent
DATASET_DIR = REPO_ROOT / "Dataset"
DEFAULT_DATASET_PATH = DATASET_DIR / "beam_dataset.h5"


def parse_args():
    p = argparse.ArgumentParser(description="Composite (rollout + physics + data) training of the Conv1d model "
                                             "on a dataset pre-generated by Dataset/Creation_dataset.py.")
    p.add_argument("--smoke-test", action="store_true",
                    help="Miniature run (few trajectories, few epochs, small groups) to check that everything "
                         "runs without error before a full, expensive run.")
    p.add_argument("--dataset-path", type=Path, default=None,
                    help=f"Path to the HDF5 dataset (default: {DEFAULT_DATASET_PATH}).")
    p.add_argument("--max-trajectories", type=int, default=None,
                    help="Load only the first N trajectories from the dataset instead of all of them "
                         "(default: 16 in --smoke-test, otherwise every trajectory in the file).")
    p.add_argument("--epochs", type=int, default=None,
                    help="Number of epochs (default: 2 in --smoke-test, otherwise Config.N_EPOCHS).")
    p.add_argument("--batch-size", type=int, default=None,
                    help="Rows per data-term batch (default: Config.BATCH_SIZE).")
    p.add_argument("--group-size", type=int, default=None,
                    help="Simulations advanced together per TBPTT rollout group "
                         "(default: 4 in --smoke-test, otherwise Config.GROUP_SIZE).")
    p.add_argument("--tbptt-hops", type=int, default=None,
                    help="Hops between weight corrections during a group's rollout "
                         "(default: 3 in --smoke-test, otherwise Config.TBPTT_HOPS).")
    p.add_argument("--lambda-data", type=float, default=None,
                    help="Weight of the one-step data term in the composite loss (default: Config.LAMBDA_DATA).")
    p.add_argument("--lambda-physics", type=float, default=None,
                    help="Weight of the wave-equation residual term (default: Config.LAMBDA_PHYSICS -- can't be "
                         "derived analytically, tune empirically against the unweighted per-term curves in "
                         "courbe_apprentissage.png).")
    p.add_argument("--lambda-rollout", type=float, default=None,
                    help="Weight of the autoregressive TBPTT rollout term (default: Config.LAMBDA_ROLLOUT).")
    p.add_argument("--early-stop-patience", type=int, default=None,
                    help="Stop training once this many consecutive epochs pass without a new best val loss "
                         "(default: Config.EARLY_STOP_PATIENCE; 0 disables early stopping, always running "
                         "the full --epochs count).")
    return p.parse_args()


def build_config(n_epochs, batch_size, group_size, tbptt_hops, lambda_data, lambda_physics, lambda_rollout,
                  early_stop_patience):
    # None -> Config's own default applies, unoverridden -- config.py stays
    # the single source of truth unless the CLI explicitly asks for a
    # different value.
    kwargs = {}
    if n_epochs is not None:
        kwargs["N_EPOCHS"] = n_epochs
    if batch_size is not None:
        kwargs["BATCH_SIZE"] = batch_size
    if group_size is not None:
        kwargs["GROUP_SIZE"] = group_size
    if tbptt_hops is not None:
        kwargs["TBPTT_HOPS"] = tbptt_hops
    if lambda_data is not None:
        kwargs["LAMBDA_DATA"] = lambda_data
    if lambda_physics is not None:
        kwargs["LAMBDA_PHYSICS"] = lambda_physics
    if lambda_rollout is not None:
        kwargs["LAMBDA_ROLLOUT"] = lambda_rollout
    if early_stop_patience is not None:
        kwargs["EARLY_STOP_PATIENCE"] = early_stop_patience
    return Config(**kwargs)


# --- Per-family showcase -----------------------------------------------
# The single pinned rollout_idx test case (used above for resume.txt's
# metrics/benchmark/PDE-consistency plots) only ever lands on ONE family --
# whichever trajectory the dataset's own test-split draw happened to
# include, often the same family run after run. To actually see how the
# network behaves on EVERY family it was trained on, dataset.load_hdf5_
# dataset already picked one held-out (val/test) trajectory per family
# (family_showcase_idx) -- roll each of those out here and render a
# propagation_onde_<family>.gif per family, straight into this run's own
# OUTPUT_DIR (not just in the standalone test/ scripts).
def make_family_animation(U, U_reel, left_bc, right_bc, cfg, gif_path):
    # Error normalized by the case's own peak amplitude (not pointwise
    # relative error, which blows up near zero-crossings) -- same rendering
    # as test/test.py, kept local for the same reason: evaluation.py is
    # shared by every rollout in this run and its plots shouldn't change for
    # all of them because of this one showcase.
    nodes = cfg.nodes
    x = np.linspace(0, cfg.L, cfg.Nx)
    frames = np.arange(0, cfg.Nt + 1, cfg.ndt)

    fig_anim, (axA, axB) = plt.subplots(2, 1, figsize=(9, 7), sharex=True)

    line_real, = axA.plot([], [], "r", lw=2, label="real")
    line_pred, = axA.plot([], [], "b--", lw=2, label="predicted")
    amp_ref = max(np.abs(U_reel[:, nodes]).max(), 1e-9)
    ymax = amp_ref * 1.2
    axA.set_xlim(0, cfg.L); axA.set_ylim(-ymax, ymax)
    axA.set_ylabel("u"); axA.legend(loc="upper right"); axA.grid(True)

    line_err, = axB.plot([], [], "k", lw=1.5, label="error / peak amplitude")
    err_frames = [np.abs(U[m, nodes] - U_reel[m, nodes]) / amp_ref for m in frames]
    err_max = max(np.max([e.max() for e in err_frames]) * 1.2, 1e-9)
    axB.set_xlim(0, cfg.L); axB.set_ylim(0, err_max)
    axB.set_xlabel("x"); axB.set_ylabel("error / peak amplitude"); axB.legend(loc="upper right"); axB.grid(True)

    title_obj = fig_anim.suptitle("")

    def update(m):
        line_real.set_data(x, U_reel[m, nodes])
        line_pred.set_data(x, U[m, nodes])
        line_err.set_data(x, np.abs(U[m, nodes] - U_reel[m, nodes]) / amp_ref)
        title_obj.set_text(f"left={bc_describe(left_bc)}  right={bc_describe(right_bc)}\n"
                        f"t = {m*cfg.dt:.3f}  (step {m})")
        return line_real, line_pred, line_err, title_obj

    anim = animation.FuncAnimation(fig_anim, update, frames=frames, interval=50, blit=False)
    anim.save(gif_path, writer="pillow", fps=20, dpi=110)
    plt.close(fig_anim)


def run_family_showcase(model, FIELDS, bc_pairs, family_showcase_idx, norm_stats, INPUTS, OUTPUTS,
                         cfg, output_dir: Path) -> dict:
    family_summary = {}
    for family, idx in family_showcase_idx.items():
        rollout = evaluation.run_rollout(model, FIELDS, bc_pairs, idx, INPUT_FIELDS, norm_stats,
                                          INPUTS, OUTPUTS, cfg)

        gif_path = output_dir / f"propagation_onde_{family}.gif"
        make_family_animation(rollout.U, rollout.U_reel, rollout.left_bc, rollout.right_bc, cfg, gif_path)

        t_axis, l2_list, linf_list, smape_list = evaluation.compute_errors(rollout, cfg)
        summary = (f"L2 final={l2_list[-1]:.3e} max={max(l2_list):.3e} | "
                   f"sMAPE final={smape_list[-1]:.1f}% max={max(smape_list):.1f}%")
        family_summary[family] = summary
        print(f"  [{family:16s}] {summary}  -> {gif_path.name}  (trajectory #{idx})")

    return family_summary


def main():
    args = parse_args()
    # Computed here (not at module level) so importing main.py just for its
    # constants (test/test*.py, check_equivalence.py...) doesn't create an
    # empty plots/simulation_.../ folder on every import.
    OUTPUT_DIR = PLOTS_DIR / f"simulation_{datetime.now():%d%m%Y_%H%M%S}"
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    n_epochs = args.epochs if args.epochs is not None else (2 if args.smoke_test else None)
    max_trajectories = args.max_trajectories if args.max_trajectories is not None else (16 if args.smoke_test else None)
    group_size = args.group_size if args.group_size is not None else (4 if args.smoke_test else None)
    tbptt_hops = args.tbptt_hops if args.tbptt_hops is not None else (3 if args.smoke_test else None)
    dataset_path = args.dataset_path if args.dataset_path is not None else DEFAULT_DATASET_PATH
    cfg = build_config(n_epochs, args.batch_size, group_size, tbptt_hops,
                        args.lambda_data, args.lambda_physics, args.lambda_rollout, args.early_stop_patience)
    set_seeds(cfg)

    patience = cfg.EARLY_STOP_PATIENCE if cfg.EARLY_STOP_PATIENCE > 0 else None

    mode = "SMOKE TEST" if args.smoke_test else "run"
    print(f"=== full_rollout_training_conv1d [{mode}] — input fields: {INPUT_FIELDS} — "
          f"dataset: {dataset_path} "
          f"({'all trajectories' if max_trajectories is None else f'first {max_trajectories} trajectories'}), "
          f"{cfg.N_EPOCHS} epochs (early-stop patience={patience}), composite loss "
          f"(rollout={cfg.LAMBDA_ROLLOUT}, physics={cfg.LAMBDA_PHYSICS}, data={cfg.LAMBDA_DATA}), "
          f"group size {cfg.GROUP_SIZE}, {cfg.TBPTT_HOPS} hops/correction, batch size {cfg.BATCH_SIZE} ===")

    # idx_train/idx_val (lists of trajectory indices) form the TBPTT rollout
    # groups (train.make_epoch_groups) -- the data term still batches over
    # df's row-level "split" column instead (via make_dataloaders below).
    # rollout_idx pins the one trajectory used for the diagnostic
    # rollout/benchmark/PDE-consistency plots further down; family_showcase_idx
    # pins one held-out trajectory per driving family for run_family_showcase.
    (df, FIELDS, INPUTS, OUTPUTS, bc_pairs, idx_train, idx_val, idx_test,
     rollout_idx, family_showcase_idx) = dataset.load_hdf5_dataset(INPUT_FIELDS, cfg, dataset_path, max_trajectories)
    print(f"{len(df):,} rows x {df.shape[1]} columns ({len(FIELDS)} trajectories)")

    norm_stats = dataset.compute_norm_stats(df, INPUTS, OUTPUTS, cfg)
    # Persisted next to model.pth (not in OUTPUT_DIR, which changes name
    # every day) so that test/check_equivalence.py always find the
    # normalization stats of the last trained model, without regenerating
    # the dataset.
    norm_stats.to_csv(PROJECT_DIR / "norm_stats.csv")

    model = ConvNet(n_lags=cfg.M_BACK, n_points=2 * cfg.SS + 1,
                     n_fields=len(INPUT_FIELDS), n_outputs=len(OUTPUTS))
    print(model)
    print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")

    # Composite training: train.train_full_rollout advances GROUP_SIZE
    # simulations at a time, hop by hop, correcting every TBPTT_HOPS hops
    # with a single backward() over the rollout + physics + data terms
    # combined (see train.py). train_loader (built the same way it always
    # was) only feeds the data term's independent one-step batches now.
    train_loader, X_val, y_val = training.make_dataloaders(df, INPUTS, OUTPUTS, norm_stats, cfg)
    train_result = train.train_full_rollout(model, FIELDS, bc_pairs, idx_train, idx_val, INPUT_FIELDS,
                                             norm_stats, INPUTS, OUTPUTS, cfg, train_loader,
                                             model_path=PROJECT_DIR / "model.pth", patience=patience)
    train.plot_rollout_training_curve(train_result, OUTPUT_DIR)

    df_test = df[df["split"] == "test"].reset_index(drop=True)
    tf_metrics = training.evaluate_teacher_forcing(model, df_test, INPUTS, OUTPUTS, norm_stats, OUTPUT_DIR)

    rollout = evaluation.run_rollout(model, FIELDS, bc_pairs, rollout_idx, INPUT_FIELDS, norm_stats,
                                      INPUTS, OUTPUTS, cfg)
    evaluation.plot_utt_uxx(rollout, cfg, OUTPUT_DIR)
    evaluation.make_rollout_animation(rollout, cfg, OUTPUT_DIR)

    errors = evaluation.compute_errors(rollout, cfg)
    t_axis, l2_list, linf_list, smape_list = errors
    evaluation.plot_rollout_error(t_axis, l2_list, linf_list, OUTPUT_DIR)
    evaluation.plot_smape(t_axis, smape_list, OUTPUT_DIR)

    bench = evaluation.benchmark_inference(model, FIELDS, INPUT_FIELDS, norm_stats, INPUTS, OUTPUTS, rollout, cfg)

    print(f"Rendering one showcase rollout per signal family into {OUTPUT_DIR} ...")
    family_summary = run_family_showcase(model, FIELDS, bc_pairs, family_showcase_idx, norm_stats,
                                          INPUTS, OUTPUTS, cfg, OUTPUT_DIR)

    extra_info = {
        "Architecture": " ".join(str(model).split()),
        "Training scheme": (f"composite: rollout (TBPTT) + physics (PDE residual) + data (one-step) -- "
                             f"lambdas=(rollout={cfg.LAMBDA_ROLLOUT}, physics={cfg.LAMBDA_PHYSICS}, "
                             f"data={cfg.LAMBDA_DATA})"),
        "Dataset": f"{dataset_path} ({len(FIELDS)} trajectories loaded)",
        "CLI args": f"epochs={cfg.N_EPOCHS}, batch_size={cfg.BATCH_SIZE}, "
                    f"group_size={cfg.GROUP_SIZE}, tbptt_hops={cfg.TBPTT_HOPS}, "
                    f"early_stop_patience={patience}",
    }
    for family, summary in family_summary.items():
        extra_info[f"Family {family}"] = summary
    evaluation.export_resume(OUTPUT_DIR, cfg, METHOD_NAME, df, INPUTS, OUTPUTS, train_result, tf_metrics,
                              rollout, bench, errors, extra_info)

    if args.smoke_test:
        ru_maxrss = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        # ru_maxrss is KiB on Linux but bytes on macOS (Darwin) -- same
        # attribute, different unit, so a single /1024 only gives MB on Linux.
        peak_rss_mb = ru_maxrss / (1024 * 1024 if sys.platform == "darwin" else 1024)
        print(f"Peak memory (smoke test): {peak_rss_mb:.0f} MB")

    print(f"Done — outputs in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
